# Generated by Django 5.1.7 on 2025-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=40)),
                ('location', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=30)),
                ('docLink', models.CharField(default='', max_length=100)),
                ('language', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
