# Generated by Django 5.1.7 on 2025-04-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0002_alter_tool_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(default=''),
        ),
    ]
