# Generated by Django 5.1.7 on 2025-04-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0003_alter_tool_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, default='', null=True)),
                ('language', models.CharField(blank=True, default='', null=True)),
                ('stargazers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('popularity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, default='', max_length=330, null=True)),
                ('homepage', models.URLField(blank=True, default='', null=True)),
            ],
        ),
    ]
