# Generated by Django 5.1.7 on 2025-04-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0004_githubtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtools',
            name='created_at',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
