# Generated by Django 5.1.7 on 2025-04-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0005_alter_githubtools_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtools',
            name='popularity',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
