# Generated by Django 5.1.7 on 2025-04-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0006_alter_githubtools_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtools',
            name='owner',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
