# Generated by Django 5.1.7 on 2025-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentation', '0007_githubtools_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtools',
            name='location',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='githubtools',
            name='type',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
